### ISSUE TITLE
Will you provide the training logs of pretrained model?

### ISSUE THREAD

**Issue by 1338199** [ashkamath/mdetr#26]

**Comment by ashkamath** [comment]
Here you go!
[effnetb3_pretraining_log.txt](https://github.com/ashkamath/mdetr/files/7205254/effnetb3_pretraining_log.txt)
[effnetb5_pretraining_log.txt](https://github.com/ashkamath/mdetr/files/7205256/effnetb5_pretraining_log.txt)
[resnet_pretraining_log.txt](https://github.com/ashkamath/mdetr/files/7205257/resnet_pretraining_log.txt)
