### ISSUE TITLE
Issues about flickr30k images dataset

### ISSUE THREAD

**Issue by 1338199** [ashkamath/mdetr#27]
I follow the flickr evalution instructions, but something wrong with the downloaded "flickr30k-images" dataset, reported error is "No such file or directory: '/data/flickr30k_images/val/100652400.jpg". Actually the "flickr30k-images" dataset I downloaded has no "val" folder. 
Same goes to the fine-tuning, there is no folder in flickr30k-images dataset named "train".

**Comment by ShoufaChen** [comment]
I met the same issue, too but I didn't seperate the `flickr-images` dir to 'train', 'val'.

I just softlink them by:
```
ln -s flickr-images train
ln -s flickr-images val
```

I think it is ok as the dataset is split by `train.txt`, `val.txt`.

However, I am not  sure about it. 
Maybe @ashkamath can help us with this issue. Is this softlink ok?

Thanks.

**Comment by ashkamath** [comment]
Yeah I guess that's fine, as long as you can reach the filename when its looked up it should be ok!
