### ISSUE TITLE
MDETR for conditional generation

### ISSUE THREAD

**Issue by heyzude** [ashkamath/mdetr#30]
Hi! Thank you for your amazing paper and work!!

I looked at your code and I guess the "decoder" in MDETR is different from the ordinary concept of decoder that people think in NLP area, which is able to generate answer in autoregressive manner, like GPT-2 or BART.

I wonder if you tried implementing MDETR with autoregressive decoder, because I'm about to do it.
If you have not, could you give me your thought whether this will work well or not?

Thank you :)

**Comment by alcinos** [comment]
Hi @heyzude 

Can you clarify what you mean by "MDETR with autoregressive decoder"? Are you trying to predict the object queries one after the other instead of all at once in parallel?
