### ISSUE TITLE
Typo in scripts/eval_lvis.py

### ISSUE THREAD

**Issue by Flaick** [ashkamath/mdetr#36]
Hello there, thank you for the high-quality code. Though I find a typo in the scripts/eval_lvis.py line 43 `utils.init_distributed_mode(args)`, I think that should be `dist.init_distributed_mode(args)`, isn't it? 

Please let me know if I misunderstand the code and run the code in the wrong way.

**Comment by alcinos** [comment]
That sounds right, yes!
