### ISSUE TITLE
Error with Runtime

### ISSUE THREAD

**Issue by panda15963** [ashkamath/mdetr#38]
![캡처](https://user-images.githubusercontent.com/45156127/133886577-3ae71f32-e049-4086-9f6c-057aa89d8967.PNG)
I just got RuntimeError with no shared folder available
Do you have any ideas to solve this error?

**Comment by TopCoder2K** [comment]
Hi, @panda15963! It looks like a repeat of [that issue](https://github.com/ashkamath/mdetr/issues/9). Have you checked it?
