### ISSUE TITLE
What are tokens?

### ISSUE THREAD

**Issue by sairaamVenkatraman** [ashkamath/mdetr#46]
I have seen the clevr annotation file, and am able to understand the fields and entries except the tokens in annotations. I would very much like to know what tokens are.
Could you help me out? Thank you

**Comment by ashkamath** [comment]
Tokens are subword units that are produced by the tokenization process. In our case we use Roberta fast tokenizer from huggingface - https://huggingface.co/docs/transformers/model_doc/roberta#transformers.RobertaTokenizerFast
