### ISSUE TITLE
No such file or directory: 'mdetr_annotations/finetune_phrasecut_train.json'

### ISSUE THREAD

**Issue by LQY404** [ashkamath/mdetr#58]
Hi, thank you for such good job.
According to the guide in https://github.com/ashkamath/mdetr/blob/main/.github/phrasecut.md, we use your model MDETR training on the PhraseCut dataset. When we download the pre-process dataset in https://zenodo.org/record/4729015/files/mdetr_annotations.tar.gz?download=1, we find that the "finetune_phrasecut_train.json" not be included in these files, can you provide this json file ? 
thanks~

**Comment by ashkamath** [comment]
Hi, 

You can find it here: https://zenodo.org/record/5519755/files/mdetr_annotations.tar.gz?download=1

Best, 
Aishwarya
