### ISSUE TITLE
preprocessd annotations

### ISSUE THREAD

**Issue by Zhangjiacheng144** [ashkamath/mdetr#59]
Hi, Thanks for your excellent work, it inspires me a lot. I want to reproduce your result for learning, but I got some problems. It seems that the link of pre-process annotations :https://zenodo.org/record/4729015/files/mdetr_annotations.tar.gz?download=1
 can't open now, that I can't download the annotations files, so could you provide a new link?

**Comment by ashkamath** [comment]
You can access it here: https://zenodo.org/record/5519755/files/mdetr_annotations.tar.gz?download=1
