### ISSUE TITLE
Cannot find phrasecut annotation files

### ISSUE THREAD

**Issue by hannahlee66** [ashkamath/mdetr#68]
Hi, Thanks for this great work! However, I've checked all files in the annotation folder: https://zenodo.org/record/4729015/files/mdetr_annotations.tar.gz?download=1, but only find `phrase_cut_unsafe_ids.pkl`, which doesn't match your training or test script. Could you update the corresponding training and test JSON script mentioned in https://github.com/ashkamath/mdetr/blob/main/datasets/phrasecut.py#L17. @ashkamath @alcinos @nguyeho7 

Many thanks in advance! Looking forward to your reply soon.

**Comment by ashkamath** [comment]
Hey, 

Sorry about that - I uploaded another folder in September on zenodo (https://zenodo.org/record/5519755#.Yd0p4xNBxb8) with all the missing annotations. You can download these at : https://zenodo.org/record/5519755/files/mdetr_annotations.tar.gz?download=1

Best, 
Aishwarya

**Comment by hannahlee66** [comment]
Thanks so much!
