### ISSUE TITLE
Doubts regarding pretraining

### ISSUE THREAD

**Issue by IISCAditayTripathi** [ashkamath/mdetr#69]
As I understand from the paper, you pretrained the whole mDETR model on image-text pairs. Did you try pertaining only the encoder model just like the Visual-BERT model?

**Comment by ashkamath** [comment]
Hey! No we did not try that, only the backbone and text encoder are pre-trained on uni-modal data. The encoder and decoder are trained only on image text pairs.

**Comment by IISCAditayTripathi** [comment]
Do you think that only training the encoder on tasks like image-text matching might help later on?

**Comment by ashkamath** [comment]
yeah an image text matching head could definitely help!
