### ISSUE TITLE
Training and Finetuning time of MDetr

### ISSUE THREAD

**Issue by ayushjain1144** [ashkamath/mdetr#7]
Hi, 

Thank you for your awesome work. I was wondering about the pre-training time (GPU hours) of your model and fine-tuning hours on maybe Refcoco or something similar. Could you please let me know about that? (It would be very helpful if you could possibly add this information for all the datasets when you find the time. Thanks!)

**Comment by ashkamath** [comment]
Hey, 
We trained the model on the pre-training dataset for 40 epochs on 32 V100 gpus, with per gpu batch size 2 (so effective batch size 64). 40 epochs took approximately 1 week.

For RefCOCO and RefCOCO+ we trained for 5 epochs, on 2 RTX8000 gpus with per gpu batch size 4. This takes about 2 days. For RefCOCOg, we trained for 3 epochs (smaller dataset) and that takes about 10-15 hours.

**Comment by mmaaz60** [comment]
Hi @ashkamath,

Could you also provide the information about the training recipe and time for Long-tailed few-shot object detection? In the repo, you seem to be training the models on 64 GPUs. Have you used a batch size of '2' per GPU in this case? And how long did it take you to train these models?

Thank you
