### ISSUE TITLE
Pre-trained model gives nan prediction in Colab

### ISSUE THREAD

**Issue by Steve-Tod** [ashkamath/mdetr#83]
Thank you for making this great work public! I'm trying to run the colab notebook but found no predictions on the test image. Then I print out the predictions of the model and found all are nan. Can you please check this?

![image](https://user-images.githubusercontent.com/26958167/178570189-25223900-b4d3-45aa-815f-e48e60856253.png)

**Comment by TopCoder2K** [comment]
Maybe, the versions of `timm` and `transformers` are unsuitable. If you look at the original notebook, you see that `timm-0.4.5` and `transformers-4.5.1` have been installed. But when you run `! pip install timm transformers` now, `timm-0.6.5` and `transformers-4.20.1` are installed.
Fixing the versions should help: `!pip install timm==0.4.5 transformers==4.5.1` (I tried and it worked).

**Comment by univanxx** [comment]
Hey, @TopCoder2K, thanks, worked for me!

**Comment by devernay** [comment]
@ashkamath why close this issue without updating the notebook?

**Comment by ashkamath** [comment]
Done now

**Comment by devernay** [comment]
it's changed on the colab notebook https://colab.research.google.com/drive/11xz5IhwqAqHj9-XAIP17yVIuJsLqeYYJ?usp=sharing
but not in the notebook that is accessible on the colab branch on github (I guess you just have to "save" the notebook in colab???)

thanks anyway!

**Comment by kyleliang919** [comment]
@ashkamath do you have insight on what might have caused this in the later version of timm? If you can give some hints to narrow down the scope, I might be able to take a look at help fix this. I am suspecting it's something to do with the latest timm.models.efficientnet.EfficientNetFeatures updates, which causes the NaN problem.
The huggingface space seems also suffering from the same issue:
https://huggingface.co/spaces/akhaliq/mdetr
