### ISSUE TITLE
How to define "Negative Tokens" ? 

### ISSUE THREAD

**Issue by jeantirole** [ashkamath/mdetr#85]
Hello, 

I am wondering how to define "negative tokens" in the dataset_dict['images'][0]['tokens_negative']. 

Is there any algorithm or rule to make "negative tokens" ? 

I couldn't find how to pattern it... ! 

Thanks, 

Best Regards,

Eric.

**Comment by ashkamath** [comment]
Hey, 
This was used in some earlier iterations of our code where we were trying to not penalize predictions to parts of the sentence that do not have noun phrases. It was not used in the final version so you don't need to worry about it! The positive tokens are the only ones that are used :)
