### ISSUE TITLE
how to define positive tokens?

### ISSUE THREAD

**Issue by jojodeng0224** [ashkamath/mdetr#87]
may I ask how to define tokens_positive and  tokens_positive_eval? what should I do when I prepare the dataset? pls help me many thanks!

**Comment by ashkamath** [comment]
Hey!
For tokens positive, it is the span of characters in the full caption that is aligned to a particular object. For example if the sentence is "the cat on the table" and you have a box for the cat and for the table, the annotations will look as follows :

for box1 : tokens_positive: [[4,7]] and for box2: [[16, 21]]

Note that it can also have 2 or more spans aligned for a given box, for example in the sentence "the cat on the table is scratching the table". In this case, the box2 would have tokens_positive as follows: [[16,21], [40,45]].

In referring expression, we do not have dense grounding for all the noun phrases in the sentence (the task is to provide one box for the whole sentence). To make it more similar to the rest of the grounding data in our dataset we choose to align the root of the sentence (extracted using spacy) as the word to align the box with. You can choose other ways to do this.


Tokens positive eval is the spans for each of the noun-phrases that need to be evaluated according to the dataset. It is set up in terms of character spans from the full caption same as above.


More concretely (from answer to another issue) :

- tokens_positive is the alignment that we use for computing the loss. It works in tandem with the boxes information: it is assumed that len(tokens_positive) == len(boxes), and that the first set of tokens corresponds to the first box and so on.

- tokens_positive_eval is used only during Flickr evaluation. It is meant to contain the phrases for which we want ranked boxes. In this case there is no boxes associated in the ground-truth (for eg when we perform evaluation on test). This should be seen as the way to query the model on a given set of phrases. 

Hope this helps! :)
