### ISSUE TITLE
RuntimeError: No shared folder available

### ISSUE THREAD

**Issue by qumengxue** [ashkamath/mdetr#9]
When I run _python run_with_submitit.py --dataset_config configs/refcoco.json  --batch_size 4  --load https://zenodo.org/record/4721981/files/pretrained_resnet101_checkpoint.pth?download=1  --ngpus 1 --nodes 2 --ema --text_encoder_lr 1e-5 --lr 5e-5_, the following error occurred: 
_Traceback (most recent call last):
  File "run_with_submitit.py", line 171, in <module>
    main()
  File "run_with_submitit.py", line 130, in main
    args.job_dir = get_shared_folder(args) / "%j"
  File "run_with_submitit.py", line 41, in get_shared_folder
    raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available_
How to deal with it?

**Comment by toku-n** [comment]
Hi @qumengxue,
How did you solved this problem?
It would be helpful if you share your solution.

**Comment by qumengxue** [comment]
> Hi @qumengxue,
> How did you solved this problem?
> It would be helpful if you share your solution.

The "coco_path" in the .json file in ./config folder need to be modified to the correct path. It seems to be the only change I do for solving this problem.

**Comment by alcinos** [comment]
@toku-n you'll likely need to also adapt the default experimental path to something that works on your cluster. 
See https://github.com/ashkamath/mdetr/blob/0e3c73fdf53d9c7ecf2cb59c10153e7911ac4349/run_with_submitit.py#L37-L41

This will fail if `/checkpoint/{user}/experiments` is not a writable path. Just change to where you want to save the experiments.

**Comment by toku-n** [comment]
Hi @qumengxue  @alcinos 
Thank you for your comment. The problem is solved.

**Comment by TopCoder2K** [comment]
Hmmm, I changed it into this:
```
user = os.getenv("USER")

if Path("/home/my_username/MDETR/mdetr/checkpoint/").is_dir():
    p = Path(f"/home/my_username/MDETR/mdetr/checkpoint/{user}/experiments")
    p.mkdir(exist_ok=True)
```
But I got the following error: 
```
Traceback (most recent call last):
  File "run_with_submitit.py", line 171, in <module>
    main()
  File "run_with_submitit.py", line 130, in main
    args.job_dir = get_shared_folder(args) / "%j"
  File "run_with_submitit.py", line 39, in get_shared_folder
    p.mkdir(exist_ok=True)
  File "/home/pchelintsev/anaconda3/envs/mdetr_env/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/my_username/MDETR/mdetr/checkpoint/my_username/experiments'
```
Only making this directory solved the problem.
