### ISSUE TITLE
[Colab Error] InvalidVersion: Invalid version: '0.10.1,<0.11'

### ISSUE THREAD

**Issue by knwoo** [ashkamath/mdetr#92]
Hi, I tried to run colab demo, but got a following error.

![image](https://user-images.githubusercontent.com/80252411/220311279-7935c975-c876-4666-bf48-726a7ac70125.png)

**Comment by vvvinit** [comment]
Replace the first cell in initial boilerplate with ```! pip install timm==0.4.5 transformers==4.5.1 packaging==21.3``` and click ```restart runtime``` once the cell has finished running.

**Comment by knwoo** [comment]
it works well. Thanks!
